
/* This file is generated by glib-mkenums, do not modify it. This code is licensed under the same license as the containing project. Note that it links to GLib, so must comply with the LGPL linking clauses. */



#include <atk.h>

/* enumerations from "atkcomponent.h" */

long unsigned int
atk_scroll_type_get_type (void)
{
    return 0;
}

/* enumerations from "atkhyperlink.h" */

long unsigned int
atk_hyperlink_state_flags_get_type (void)
{
    return 0;
}

/* enumerations from "atkobject.h" */

long unsigned int
atk_role_get_type (void)
{
    return 0;
}

long unsigned int
atk_layer_get_type (void)
{
    return 0;
}

/* enumerations from "atkrelationtype.h" */

long unsigned int
atk_relation_type_get_type (void)
{
    return 0;
}

/* enumerations from "atkstate.h" */

long unsigned int
atk_state_type_get_type (void)
{
    return 0;
}

/* enumerations from "atktext.h" */

long unsigned int
atk_text_attribute_get_type (void)
{
    return 0;
}

long unsigned int
atk_text_boundary_get_type (void)
{
    return 0;
}

long unsigned int
atk_text_granularity_get_type (void)
{
    return 0;
}

long unsigned int
atk_text_clip_type_get_type (void)
{
    return 0;
}

/* enumerations from "atkutil.h" */

long unsigned int
atk_key_event_type_get_type (void)
{
    return 0;
}

long unsigned int
atk_coord_type_get_type (void)
{
    return 0;
}

/* enumerations from "atkvalue.h" */

long unsigned int
atk_value_type_get_type (void)
{
    return 0;
}

/* Generated data ends here */

