
/* This file is generated by glib-mkenums, do not modify it. This code is licensed under the same license as the containing project. Note that it links to GLib, so must comply with the LGPL linking clauses. */

#include "config.h"

#include <atk.h>

/* enumerations from "atkcomponent.h" */

GType
atk_scroll_type_get_type (void)
{
    return 0;
}

/* enumerations from "atkhyperlink.h" */

GType
atk_hyperlink_state_flags_get_type (void)
{
    return 0;
}

/* enumerations from "atkobject.h" */

GType
atk_role_get_type (void)
{
    return 0;
}

GType
atk_layer_get_type (void)
{
    return 0;
}

/* enumerations from "atkrelationtype.h" */

GType
atk_relation_type_get_type (void)
{
    return 0;
}

/* enumerations from "atkstate.h" */

GType
atk_state_type_get_type (void)
{
    return 0;
}

/* enumerations from "atktext.h" */

GType
atk_text_attribute_get_type (void)
{
    return 0;
}

GType
atk_text_boundary_get_type (void)
{
    return 0;
}

GType
atk_text_granularity_get_type (void)
{
    return 0;
}

GType
atk_text_clip_type_get_type (void)
{
    return 0;
}

/* enumerations from "atkutil.h" */

GType
atk_key_event_type_get_type (void)
{
    return 0;
}

GType
atk_coord_type_get_type (void)
{
    return 0;
}

/* enumerations from "atkvalue.h" */

GType
atk_value_type_get_type (void)
{
    return 0;
}

/* Generated data ends here */

