/* This file is generated by glib-genmarshal, do not modify it. This code is licensed under the same license as the containing project. Note that it links to GLib, so must comply with the LGPL linking clauses. */
#pragma once

/* VOID:INT,INT (../atk/atkmarshal.list:25) */
void atk_marshal_VOID__INT_INT ();

/* VOID:INT,INT,STRING (../atk/atkmarshal.list:26) */
void atk_marshal_VOID__INT_INT_STRING ();

/* VOID:INT,INT,INT,STRING (../atk/atkmarshal.list:27) */
void atk_marshal_VOID__INT_INT_INT_STRING ();

/* VOID:STRING,BOOLEAN (../atk/atkmarshal.list:28) */
void atk_marshal_VOID__STRING_BOOLEAN ();

/* VOID:DOUBLE,STRING (../atk/atkmarshal.list:29) */
void atk_marshal_VOID__DOUBLE_STRING ();


