/*
 * Autogenerated by the Meson build system.
 * Do not edit, your changes will be lost.
 */

#pragma once

#define GETTEXT_PACKAGE "atk10"

#define HAVE_BIND_TEXTDOMAIN_CODESET 1

#define VERSION "2.38.1"

#define _ATK_EXTERN __attribute__((visibility("default"))) extern

